export { default as FRButton } from './FRButton.vue'
export { default as FRInput } from './FRInput.vue'
export { default as FRSeparator } from './FRSeparator.vue'
export { default as FRTable } from './FRTable.vue'
export { default as FRTableHeader } from './FRTableHeader.vue'
export { default as FRTableBody } from './FRTableBody.vue'
export { default as FRTableRow } from './FRTableRow.vue'
export { default as FRTableHead } from './FRTableHead.vue'
export { default as FRTableCell } from './FRTableCell.vue'
export { default as FRLabel } from './FRLabel.vue'
export { default as FRSwitch } from './FRSwitch.vue'
export { default as FRTooltip } from './FRTooltip.vue'
export { default as FROverflowTooltipText } from './FROverflowTooltipText.vue'

export * from './select'
export * from './dialog'
